name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy {{ secrets.host }} {{ secrets.password }}
      - run: cd dist/project && rsync -avzhe sshpass -p ${{ secrets.PASSWORD }} ssh . ${{ secrets.HOST }}:/workar6g.beget.tech/public_html

